project:
  type: website
  output-dir: docs

website:
  title: "Tokyo.R #120"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: simplex
    toc: true
    toc-depth: 4
    number-sections: false
